PRICE_MIN = 2_500_000
PRICE_MAX = 3_000_000
MONTHLY_INCOME = 30_000  # AED combined household
DB_PATH = "properties.db"

LOCATIONS = {
    "The Views": {
        "bayut_slug": "the-views",
        "pf_slug": "the-views",
        "avg_price_psf": 1650,
        "service_charge_psf": 18,
        "lat": 25.0667,
        "lon": 55.1667,
    },
    "Dubai Hills": {
        "bayut_slug": "dubai-hills-estate",
        "pf_slug": "dubai-hills-estate",
        "avg_price_psf": 1900,
        "service_charge_psf": 22,
        "lat": 25.1128,
        "lon": 55.2292,
    },
    "Arabian Ranches 1": {
        "bayut_slug": "arabian-ranches",
        "pf_slug": "arabian-ranches",
        "avg_price_psf": 1100,
        "service_charge_psf": 16,
        "lat": 25.0544,
        "lon": 55.2706,
    },
    "Studio City": {
        "bayut_slug": "dubai-studio-city",
        "pf_slug": "dubai-studio-city",
        "avg_price_psf": 1050,
        "service_charge_psf": 14,
        "lat": 25.0657,
        "lon": 55.1968,
    },
    "Motorcity": {
        "bayut_slug": "motor-city",
        "pf_slug": "motor-city",
        "avg_price_psf": 1000,
        "service_charge_psf": 13,
        "lat": 25.0489,
        "lon": 55.2122,
    },
    "JLT": {
        "bayut_slug": "jumeirah-lake-towers-jlt",
        "pf_slug": "jumeirah-lake-towers-jlt",
        "avg_price_psf": 1350,
        "service_charge_psf": 17,
        "lat": 25.0693,
        "lon": 55.1390,
    },
}

BANKS = [
    {
        "name": "Dubai Islamic Bank (DIB)",
        "type": "Islamic",
        "fixed_rate": 3.49,
        "fixed_period": 1,
        "variable_rate_margin": 1.35,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 1.0,
        "min_salary": 15_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["Shariah compliant", "Life takaful included", "No penalty after year 3"],
    },
    {
        "name": "Abu Dhabi Islamic Bank (ADIB)",
        "type": "Islamic",
        "fixed_rate": 3.69,
        "fixed_period": 1,
        "variable_rate_margin": 1.40,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 1.0,
        "min_salary": 15_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["Shariah compliant", "Free valuation", "Flexible repayment"],
    },
    {
        "name": "Emirates Islamic",
        "type": "Islamic",
        "fixed_rate": 3.69,
        "fixed_period": 2,
        "variable_rate_margin": 1.45,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 1.0,
        "min_salary": 15_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["Shariah compliant", "2-year fixed rate", "Cashback offer"],
    },
    {
        "name": "First Abu Dhabi Bank (FAB)",
        "type": "Conventional",
        "fixed_rate": 3.75,
        "fixed_period": 1,
        "variable_rate_margin": 1.45,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 0.5,
        "min_salary": 15_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["Free property valuation", "Low processing fee", "Salary transfer optional"],
    },
    {
        "name": "ADCB",
        "type": "Conventional",
        "fixed_rate": 3.75,
        "fixed_period": 1,
        "variable_rate_margin": 1.50,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 1.0,
        "min_salary": 15_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["Touchpoints rewards", "Flexible drawdown", "Offset account option"],
    },
    {
        "name": "Emirates NBD",
        "type": "Conventional",
        "fixed_rate": 3.99,
        "fixed_period": 1,
        "variable_rate_margin": 1.50,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 1.0,
        "min_salary": 15_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["Largest bank network", "Digital-first process", "Salary transfer required"],
    },
    {
        "name": "Mashreq Bank",
        "type": "Conventional",
        "fixed_rate": 3.99,
        "fixed_period": 1,
        "variable_rate_margin": 1.55,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 1.0,
        "min_salary": 15_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["Quick approval", "Salary transfer bonus", "Zero fee refinancing after 2 years"],
    },
    {
        "name": "HSBC UAE",
        "type": "Conventional",
        "fixed_rate": 3.99,
        "fixed_period": 2,
        "variable_rate_margin": 1.49,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 0.0,
        "min_salary": 15_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["No processing fee", "2-year fixed rate", "Premier banking benefits"],
    },
    {
        "name": "RAK Bank",
        "type": "Conventional",
        "fixed_rate": 4.24,
        "fixed_period": 1,
        "variable_rate_margin": 1.75,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 1.0,
        "min_salary": 10_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["Low minimum salary", "Fast approval", "Accepts all nationalities"],
    },
    {
        "name": "Commercial Bank of Dubai (CBD)",
        "type": "Conventional",
        "fixed_rate": 3.99,
        "fixed_period": 1,
        "variable_rate_margin": 1.50,
        "max_tenure": 25,
        "max_ltv_resident": 80,
        "max_ltv_nonresident": 65,
        "processing_fee_pct": 1.0,
        "min_salary": 15_000,
        "early_settlement_fee_pct": 1.0,
        "features": ["Dedicated relationship manager", "Flexible repayment options", "Cashback on fees"],
    },
]

NEARBY_AMENITIES = {
    "Metro Stations": {
        "Internet City Metro": (25.0943, 55.1528),
        "Media City Metro": (25.0983, 55.1578),
        "DAMAC Metro (Business Bay)": (25.1851, 55.2641),
        "Al Khail Metro": (25.1120, 55.1847),
        "Nakheel Metro (JLT)": (25.0706, 55.1391),
        "DMCC Metro (JLT)": (25.0695, 55.1396),
        "Sobha Realty Metro": (25.0765, 55.1393),
    },
    "Schools": {
        "Repton School Dubai": (25.0678, 55.1657),
        "Dubai British School": (25.0582, 55.2122),
        "GEMS World Academy": (25.1138, 55.2278),
        "Dubai Hills Community School": (25.1178, 55.2289),
        "Kings School Al Barsha": (25.1038, 55.1985),
        "JESS Arabian Ranches": (25.0542, 55.2698),
        "Sunmarke School JVC": (25.0612, 55.1968),
    },
    "Hospitals": {
        "Mediclinic Parkview": (25.0612, 55.2102),
        "King's College Hospital Dubai": (25.1108, 55.2289),
        "Mediclinic Meadows": (25.0667, 55.1589),
        "Emirates Hospital Motor City": (25.0478, 55.2112),
        "NMC Royal Hospital": (25.0589, 55.1978),
    },
    "Malls": {
        "Mall of the Emirates": (25.1181, 55.2008),
        "Dubai Hills Mall": (25.1152, 55.2332),
        "City Walk": (25.1886, 55.2381),
        "JLT Cluster": (25.0689, 55.1398),
        "Cityland Mall": (25.0623, 55.1998),
        "Arabian Center": (25.0612, 55.2698),
    },
}
